import json

with open(r'C:\Users\user\Chunk-Picker-Mod\scripts\monster_stats.json') as f:
    stats = json.load(f)

manual = {
    "Spider": {"hp": 1, "def": 1, "def_bonus": -42},
    "Scorpion": {"hp": 17, "def": 10, "def_bonus": 0},
    "Minotaur": {"hp": 10, "def": 5, "def_bonus": 0},
    "Wolf": {"hp": 15, "def": 9, "def_bonus": 0},
    "White wolf": {"hp": 28, "def": 14, "def_bonus": 0},
    "Monk": {"hp": 15, "def": 7, "def_bonus": 0},
    "Monk of Zamorak": {"hp": 30, "def": 24, "def_bonus": 0},
    "Pirate": {"hp": 20, "def": 12, "def_bonus": 0},
    "Pirate#Plain": {"hp": 20, "def": 12, "def_bonus": 0},
    "Pirate (Theiving)": {"hp": 20, "def": 12, "def_bonus": 0},
    "Ogre": {"hp": 60, "def": 30, "def_bonus": 0},
    "Steel dragon": {"hp": 210, "def": 215, "def_bonus": 70},
    "Poison spider": {"hp": 10, "def": 5, "def_bonus": 0},
    "Vorkath": {"hp": 750, "def": 214, "def_bonus": 26},
    "Muttadile": {"hp": 400, "def": 200, "def_bonus": 70},
    "Tekton": {"hp": 600, "def": 205, "def_bonus": 120},
    "Vasa Nistirio": {"hp": 600, "def": 175, "def_bonus": 50},
    "Skeletal Mystic": {"hp": 200, "def": 120, "def_bonus": 0},
    "Vanguard": {"hp": 300, "def": 150, "def_bonus": 50},
    "Vespula": {"hp": 200, "def": 150, "def_bonus": 0},
    "Scavenger beast": {"hp": 20, "def": 1, "def_bonus": 0},
    "Sotetseg": {"hp": 4000, "def": 200, "def_bonus": 100},
    "Pestilent Bloat": {"hp": 1500, "def": 100, "def_bonus": 100},
    "Nylocas Vasilias": {"hp": 2500, "def": 50, "def_bonus": 0},
    "The Maiden of Sugadinti": {"hp": 3500, "def": 200, "def_bonus": 0},
    "Verzik Vitur": {"hp": 6525, "def": 200, "def_bonus": 60},
    "Vardorvis": {"hp": 700, "def": 215, "def_bonus": 60},
    "The Leviathan": {"hp": 800, "def": 200, "def_bonus": 40},
    "The Whisperer": {"hp": 700, "def": 220, "def_bonus": 80},
    "Scurrius": {"hp": 200, "def": 60, "def_bonus": 0},
    "Phantom Muspah": {"hp": 400, "def": 180, "def_bonus": 30},
    "Zalcano": {"hp": 600, "def": 200, "def_bonus": 0},
    "Nail beast": {"hp": 69, "def": 56, "def_bonus": 0},
    "Vyrewatch": {"hp": 125, "def": 75, "def_bonus": 0},
    "Al-Kharid warrior": {"hp": 19, "def": 7, "def_bonus": 0},
    "Rooster": {"hp": 3, "def": 1, "def_bonus": -42},
    "Seagull": {"hp": 3, "def": 1, "def_bonus": -42},
    "Seagull#Icyene Graveyard": {"hp": 3, "def": 1, "def_bonus": -42},
    "Golem": {"hp": 12, "def": 5, "def_bonus": 0},
    "River troll": {"hp": 66, "def": 39, "def_bonus": 0},
    "Tree spirit": {"hp": 54, "def": 35, "def_bonus": 0},
    "Shade": {"hp": 29, "def": 14, "def_bonus": 0},
    "Thief": {"hp": 19, "def": 8, "def_bonus": 0},
    "Thief#Plain": {"hp": 19, "def": 8, "def_bonus": 0},
    "Giant scarab": {"hp": 120, "def": 80, "def_bonus": 0},
    "Scarab mage": {"hp": 60, "def": 40, "def_bonus": 0},
    "Scarab swarm": {"hp": 10, "def": 1, "def_bonus": 0},
    "Tortured gorilla": {"hp": 113, "def": 70, "def_bonus": 0},
    "Wallasalki": {"hp": 65, "def": 40, "def_bonus": 0},
    "Swamp snake": {"hp": 10, "def": 5, "def_bonus": 0},
    "Monkey Zombie": {"hp": 55, "def": 30, "def_bonus": 0},
    "Desert snake": {"hp": 1, "def": 1, "def_bonus": -42},
    "Kebbit": {"hp": 5, "def": 1, "def_bonus": 0},
    "Mosquito swarm": {"hp": 6, "def": 1, "def_bonus": 0},
    "Undead Lumberjack": {"hp": 10, "def": 5, "def_bonus": 0},
    "Me": {"hp": 50, "def": 30, "def_bonus": 0},
    "Duke": {"hp": 200, "def": 150, "def_bonus": 0},
    "Forester": {"hp": 20, "def": 10, "def_bonus": 0},
    "Frost crab": {"hp": 15, "def": 5, "def_bonus": 0},
    "Zombie pirate": {"hp": 55, "def": 30, "def_bonus": 0},
    "Sea troll": {"hp": 65, "def": 40, "def_bonus": 0},
    "Rock golem (monster)": {"hp": 159, "def": 100, "def_bonus": 0},
    "Penance Fighter": {"hp": 30, "def": 20, "def_bonus": 0},
    "Penance Healer": {"hp": 27, "def": 15, "def_bonus": 0},
    "Penance Ranger": {"hp": 30, "def": 20, "def_bonus": 0},
    "Mounted terrorbird gnome": {"hp": 20, "def": 10, "def_bonus": 0},
    "Hazeel Cultist": {"hp": 20, "def": 10, "def_bonus": 0},
    "Black knight (Port Sarim Jail)": {"hp": 29, "def": 18, "def_bonus": 0},
    "Nazastarool": {"hp": 80, "def": 50, "def_bonus": 0},
    "Skeleton fremennik": {"hp": 25, "def": 12, "def_bonus": 0},
    "Undead one#Skeleton": {"hp": 25, "def": 15, "def_bonus": 0},
    "Mummy#Level 84": {"hp": 80, "def": 60, "def_bonus": 0},
    "Mummy#Level 98": {"hp": 95, "def": 70, "def_bonus": 0},
    "Mummy#Level 103": {"hp": 100, "def": 75, "def_bonus": 0},
    "Skeleton (Tarn's Lair)#Low level": {"hp": 25, "def": 12, "def_bonus": 0},
    "Skeleton (Tarn's Lair)#Mid level": {"hp": 50, "def": 30, "def_bonus": 0},
    "Skeleton (Tarn's Lair)#High level": {"hp": 75, "def": 50, "def_bonus": 0},
    "Zombie (Kourend)": {"hp": 28, "def": 15, "def_bonus": 0},
    "Zombie (Tarn's Lair)#Low level": {"hp": 25, "def": 12, "def_bonus": 0},
    "Zombie (Tarn's Lair)#Mid level": {"hp": 50, "def": 30, "def_bonus": 0},
    "Zombie (Tarn's Lair)#High level": {"hp": 75, "def": 50, "def_bonus": 0},
    "Apmeken (monster)": {"hp": 150, "def": 100, "def_bonus": 0},
    "Scabaras (monster)": {"hp": 150, "def": 100, "def_bonus": 0},
    "Het (monster)": {"hp": 150, "def": 100, "def_bonus": 0},
    "Colossal Chocco Chicken": {"hp": 50, "def": 20, "def_bonus": 0},
    "Woman (West Ardougne)": {"hp": 20, "def": 7, "def_bonus": 0},
    "Snake (Varlamore)": {"hp": 10, "def": 5, "def_bonus": 0},
    "Scorpion (Sailing)": {"hp": 17, "def": 10, "def_bonus": 0},
    "Moss giant (Iorwerth Dungeon)": {"hp": 60, "def": 30, "def_bonus": 0},
    "Tortoise#Without riders": {"hp": 79, "def": 60, "def_bonus": 30},
    "Jonny the beard": {"hp": 10, "def": 5, "def_bonus": 0},
    "Afflicted": {"hp": 40, "def": 20, "def_bonus": 0},
    "Blood Reaver": {"hp": 35, "def": 20, "def_bonus": 0},
    "Boar": {"hp": 12, "def": 5, "def_bonus": 0},
    "Bird": {"hp": 1, "def": 1, "def_bonus": -42},
    "Camp dweller": {"hp": 15, "def": 5, "def_bonus": 0},
    "Catablepon": {"hp": 64, "def": 35, "def_bonus": 0},
    "Angry giant rat": {"hp": 10, "def": 5, "def_bonus": 0},
    "Aviansie": {"hp": 80, "def": 60, "def_bonus": 10},
    "Bandit (Bandit Camp)": {"hp": 28, "def": 15, "def_bonus": 0},
    "Dark wizard#Higher level": {"hp": 25, "def": 12, "def_bonus": 0},
    "Dark warrior#Zeah": {"hp": 15, "def": 8, "def_bonus": 0},
    "Dagannoth": {"hp": 35, "def": 20, "def_bonus": 0},
    "Damis": {"hp": 100, "def": 80, "def_bonus": 0},
    "Cyclops": {"hp": 56, "def": 40, "def_bonus": 0},
    "Cyclops (Catacombs of Kourend)": {"hp": 56, "def": 40, "def_bonus": 0},
    "Cyclops#Warriors' Guild Basement": {"hp": 56, "def": 40, "def_bonus": 0},
}

stats.update(manual)

with open(r'C:\Users\user\Chunk-Picker-Mod\scripts\monster_stats.json', 'w') as f:
    json.dump(stats, f, indent=2, sort_keys=True)

with open(r'C:\Users\user\Chunk-Picker-Mod\scripts\monster_names.json') as f:
    all_names = json.load(f)
still_missing = [n for n in all_names if n not in stats]
print("Total: %d/%d (%.1f%%)" % (len(stats), len(all_names), 100*len(stats)/len(all_names)))
print("Still missing: %d" % len(still_missing))
if still_missing:
    print(still_missing)
