// Shop sell multipliers (shops not listed default to 1.3)
const shopMarkups = {
    'Aaron\'s Archery Appendages.': 1.0,
    'Agelus\' Farm Shop': 1.0,
    'Ak-Haranu\'s Exotic Shop.': 1.0,
    'Aleck\'s Hunter Emporium.': 1.2,
    'Ali\'s Discount Wares.': 1.0,
    'Alice\'s Farming shop.': 1.0,
    'Allanna\'s Farming Shop': 1.0,
    'Amelia\'s Seed Shop': 1.0,
    'Amlodd\'s Magical Supplies': 1.0,
    'Aneirin\'s Armour': 1.0,
    'Arcuani\'s Archery Supplies': 1.0,
    'Ardougne Baker\'s Stall.': 1.0,
    'Ardougne Fur Stall.': 1.2,
    'Ardougne Gem Stall.': 1.5,
    'Ardougne Silver Stall.': 1.0,
    'Ardougne Spice Stall.': 1.0,
    'Armour Shop (Jatizso)': 1.1,
    'Armoury': 1.5,
    'Arnold\'s Eclectic Supplies.': 1.05,
    'Artima\'s Crafting Supplies': 1.0,
    'Aubury\'s Rune Shop.': 1.0,
    'Baba Yaga\'s Magic Shop.': 1.0,
    'Bandit Bargains': 1.0,
    'Bandit Duty Free': 0.9,
    'Battle Runes#Post-miniquest': 1.0,
    'Battle Runes#Pre-miniquest': 1.0,
    'Beach Cocktails': 1.0,
    'Bedabin Village Bartering': 1.2,
    'Betty\'s Magic Emporium.': 1.0,
    'Blades by Urbi.': 1.5,
    'Blair\'s Armour': 1.0,
    'Blurberry Bar': 1.0,
    'Bob\'s Brilliant Axes.': 1.0,
    'Branwen\'s Farming Shop': 1.0,
    'Brian\'s Archery Supplies.': 1.0,
    'Brian\'s Battleaxe Bazaar.': 1.0,
    'Briget\'s Weapons': 1.0,
    'Cam Torum Blacksmith': 1.0,
    'Carefree Crafting Stall': 1.5,
    'Cassie\'s Shield Shop.': 1.0,
    'Cobado\'s Groceries': 1.0,
    'Conara\'s Jewels': 1.0,
    'Contraband yak produce.': 1.1,
    'Crossbow Shop (Dwarven Mine)': 3.6,
    'Crossbow Shop (Keldagrim)': 3.0,
    'Crossbow Shop (White Wolf Mountain)': 3.6,
    'Daga\'s Scimitar Smithy': 1.0,
    'Dancing Donkey Inn': 1.0,
    'Dargaud\'s Bow and Arrows.': 1.0,
    'Darkmeyer Lantern Shop': 1.2,
    'Darkmeyer Meat Shop': 1.0,
    'Darren\'s Wilderness Cape Shop.': 1.0,
    'Daryl\'s Ranging Surplus': 1.0,
    'Deepfin Inn': 1.0,
    'Deepfin Point Ore Exchange': 1.1,
    'Diango\'s Toy Store': 1.5,
    'Dodgy Mike\'s Second Hand Clothing.': 1.0,
    'Dommik\'s Crafting Store.': 1.0,
    'Draynor Seed Market': 1.2,
    'Drogo\'s Mining Emporium.': 1.0,
    'Durrik\'s Goods': 2.5,
    'Edmond\'s Wilderness Cape Shop.': 1.0,
    'Edward\'s Wilderness Cape Shop.': 1.0,
    'Elder Blunn\'s Spear and Shield Stall': 1.0,
    'Elder Coco\'s Crafting Stall': 1.0,
    'Elder Krill\'s Fishing Stall': 1.0,
    'Elder Raley\'s Herblore Stall': 1.0,
    'Elder Strom\'s Hunting Stall': 1.2,
    'Elgan\'s Exceptional Staffs!': 1.0,
    'Emelio\'s Kebab Shop': 1.0,
    'Fairy Fixit\'s Fairy Enchantment': 1.0,
    'Falador Party Room': 1.0,
    'Faustus\' Fruit and Veg': 1.0,
    'Fernahei\'s Fishing Hut.': 1.0,
    'Fight Arena Bar': 1.0,
    'Filamina\'s Wares': 1.0,
    'Fine Fashions': 1.0,
    'Fishing Guild Shop.': 1.0,
    'Floria\'s Fashion': 1.0,
    'Flosi\'s Fishmongers': 1.1,
    'Flying Horse Inn': 1.0,
    'Flynn\'s Mace Market.': 1.0,
    'Food Store': 1.0,
    'Fortis Baker\'s Stall': 1.0,
    'Fortis Blacksmith': 1.0,
    'Fortis Fur Stall': 1.2,
    'Fortis Gem Stall': 1.5,
    'Fortis Silk Stall': 0.5,
    'Fortis Spice Stall': 1.0,
    'Frankie\'s Fishing Emporium': 1.0,
    'Fremennik Fur Trader': 1.2,
    'Frenita\'s Cookery Shop.': 1.0,
    'Frincos\' Fabulous Herb Store.': 1.0,
    'Funch\'s Fine Groceries': 1.0,
    'Gabooty\'s Tai Bwo Wannai Cooperative.': 1.2,
    'Gaius\' Two Handed Shop.': 1.0,
    'Garden Centre': 1.0,
    'Gem Trader.': 1.0,
    'General Store (Canifis)': 2.0,
    'Gerrant\'s Fishy Business.': 1.0,
    'Gianne\'s Restaurant': 1.0,
    'Grace\'s Graceful Clothing': 1.0,
    'Grand Tree Groceries': 1.0,
    'Green Gemstone Gems': 1.5,
    'Greengrocer of Miscellania': 1.2,
    'Gulluck and Sons': 1.0,
    'Gwyn\'s Mining Emporium': 1.0,
    'Hamab\'s Crafting Emporium': 1.0,
    'Happy Heroes\' H\'emporium.': 1.0,
    'Harpoon Joe\'s House of \'Rum\'.': 1.0,
    'Harry\'s Fishing Shop.': 1.0,
    'Helmet Shop.': 1.0,
    'Henderson\'s Catch of the Day': 1.0,
    'Herquin\'s Gems.': 1.0,
    'Hickton\'s Archery Emporium.': 1.0,
    'Horvik\'s Armour Shop.': 1.0,
    'Huita\'s Herbal Supplies': 1.0,
    'Ian\'s Wilderness Cape Shop.': 1.0,
    'Ifaba\'s General Store': 1.0,
    'Iorwerth\'s Arms': 1.5,
    'Irksol (shop)': 0.5,
    'Ishmael\'s Fish He Sells': 1.0,
    'Island Greengrocer': 1.2,
    'Ivan\'s Supplies': 1.0,
    'Iwan\'s Maces': 1.0,
    'Jamila\'s Craft Stall.': 1.5,
    'Jatix\'s Herblore Shop.': 1.0,
    'Jiminua\'s Jungle Store.': 1.5,
    'Jukat (shop)': 1.0,
    'Karamja Wines, Spirits, and Beers.': 1.0,
    'Kastori Farming Supplies': 1.0,
    'Keepa Kettilon\'s store': 1.1,
    'Keldagrim\'s Best Bread': 1.5,
    'Kenelme\'s Wares': 1.0,
    'Khazard General Store': 1.4,
    'King Narnode\'s Royal Seed Pods': 0.1,
    'Kourend Castle Baker\'s Stall.': 1.0,
    'Kourend Castle Gem Stall.': 1.0,
    'Larry\'s Wilderness Cape Shop.': 1.0,
    'Leenz\'s General Supplies': 1.1,
    'Legends Guild General Store.': 1.55,
    'Legends Guild Shop of Useful Items.': 1.5,
    'Leon\'s Prototype Crossbow.': 1.0,
    'Little Munty\'s Little Shop': 1.1,
    'Little Shop of Horace': 1.25,
    'Lliann\'s Wares': 1.0,
    'Logava Gricoller\'s Cooking Supplies': 1.0,
    'Louie\'s Armoured Legs Bazaar.': 1.0,
    'Lovecraft\'s Tackle': 1.0,
    'Lowe\'s Archery Emporium': 1.0,
    'Lunami\'s Axe Shop': 1.0,
    'Lundail\'s Arena-side Rune Shop.': 1.0,
    'Mage Arena Staffs.': 1.0,
    'Magic Guild Store (Mystic Robes)': 1.0,
    'Magic Guild Store (Runes and Staves)': 1.0,
    'Martin Thwait\'s Lost and Found.': 1.0,
    'Miltog\'s Lamps': 1.5,
    'Mining Guild Mineral Exchange': 1.0,
    'Miscellanian Clothes Shop': 1.0,
    'Miscellanian Food Shop': 1.0,
    'Mistrock Mining Supplies': 1.0,
    'Moon Clan Fine Clothes.': 1.0,
    'Moon Clan General Store.': 1.0,
    'Mount Karuulm Weapon Shop': 1.0,
    'Multicannon parts for sale': 1.07,
    'Myths\' Guild Armoury': 1.5,
    'Myths\' Guild Herbalist': 1.0,
    'Myths\' Guild Weaponry': 1.0,
    'Nardah Hunter Shop.': 1.2,
    'Nardok\'s Bone Weapons': 1.0,
    'Nathifa\'s Bake Stall.': 1.0,
    'Ned\'s Handmade Rope (100% Wool - not yak, honest!)': 1.0,
    'Neil\'s Wilderness Cape Shop.': 1.0,
    'Neitiznot supplies.': 1.05,
    'Nurmof\'s Pickaxe Shop.': 1.0,
    'Obli\'s General Store.': 1.5,
    'Oobapohk\'s Javelin Store': 1.0,
    'Ore seller.': 1.5,
    'Ore store': 1.1,
    'Pelters\' Veg Stall': 1.0,
    'Perry\'s Chop-chop Shop': 3.2,
    'Petrified Pete\'s Ore Shop': 1.0,
    'Picaria\'s Fishing Shop': 1.0,
    'Pie Shop': 1.0,
    'Pollnivneach general store.': 1.0,
    'Port Roberts Cannonball Stall': 2.5,
    'Port Roberts Fish Stall': 1.0,
    'Port Roberts Fur Stall': 1.2,
    'Port Roberts Gem Stall': 1.0,
    'Port Roberts Ore Stall': 1.1,
    'Port Roberts Silver Stall': 1.0,
    'Port Roberts Spice Stall': 1.0,
    'Port Roberts Veg Stall': 1.0,
    'Prifddinas Foodstuffs': 1.0,
    'Prifddinas Gem Stall': 1.0,
    'Prifddinas Herbal Supplies': 1.0,
    'Prifddinas Silver Stall': 1.0,
    'Prifddinas Spice Stall': 1.0,
    'Prospector Percy\'s Nugget Shop': 1.0,
    'Raetul and Co\'s Cloth Store.': 1.0,
    'Ranael\'s Super Skirt Store.': 1.0,
    'Rasolo the Wandering Merchant': 2.0,
    'Rat & Bat': 1.0,
    'Razmire Builders Merchants.': 1.05,
    'Regath\'s Wares': 1.4,
    'Reldak\'s Leather Armour': 1.0,
    'Richard\'s Farming shop.': 1.0,
    'Richard\'s Wilderness Cape Shop.': 1.0,
    'Rok\'s Chocs Box.': 1.0,
    'Rommik\'s Crafty Supplies.': 1.0,
    'Salius\' Armour Shop': 1.0,
    'Sam\'s Wilderness Cape Shop.': 1.0,
    'Sarah\'s Farming shop.': 1.0,
    'Scavvo\'s Rune Store.': 1.0,
    'Sebamo\'s Sublime Staffs': 1.0,
    'Seddu\'s Adventurer\'s Store.': 0.95,
    'Shantay Pass Shop': 1.0,
    'Shayzien Styles': 1.0,
    'Shields of Mistrock': 1.0,
    'Shop of Distaste': 1.0,
    'Sian\'s Ranged Weaponry': 1.0,
    'Silver Cog Silver Stall': 1.5,
    'Simon\'s Wilderness Cape Shop.': 1.0,
    'Slayer Equipment (shop)': 1.0,
    'Smithing Smith\'s Shop.': 1.0,
    'Solihib\'s Food Stall': 1.0,
    'Sulisal\'s Superb Fishing Store': 1.0,
    'Tal Teklan Rune Shop': 1.0,
    'Tamayu\'s Spear Stall': 1.0,
    'The Asp & Snake Bar.': 1.0,
    'The Cloak and Stagger': 1.0,
    'The Deeper Lode': 1.4,
    'The Esoterican Arms': 1.0,
    'The Golden Field': 1.0,
    'The Haymaker\'s Arms': 1.0,
    'The Lighthouse Store': 1.1,
    'The Other Inn.': 1.0,
    'The Runic Emporium': 1.0,
    'The Sheared Ram': 1.0,
    'The Spice Is Right.': 1.5,
    'The Toad and Chicken': 1.0,
    'Thessalia\'s Fine Clothes.': 1.0,
    'Thirus Urkar\'s Fine Dynamite Store': 11.5,
    'Thyria\'s Wares': 1.0,
    'Tiadeche\'s Karambwan Stall': 0.55,
    'Tizoro\'s Pickaxes': 1.0,
    'Toci\'s Gem Store': 1.0,
    'Tony\'s Pizza Bases': 1.0,
    'Trader Stan\'s Trading Post': 2.5,
    'Tutab\'s Magical Market': 1.0,
    'Two Feet Charley\'s Fish Shop.': 1.0,
    'Tynan\'s Fishing Supplies': 1.0,
    'TzHaar-Hur-Lek\'s Ore and Gem Store': 1.5,
    'TzHaar-Hur-Rin\'s Ore and Gem Store': 1.5,
    'TzHaar-Hur-Tel\'s Equipment Store': 1.5,
    'TzHaar-Hur-Zal\'s Equipment Store': 1.5,
    'TzHaar-Mej-Roh\'s Rune Store': 1.5,
    'Vanessa\'s Farming shop.': 1.0,
    'Vannah\'s Farming Stall': 1.0,
    'Varrock Swordshop': 1.0,
    'Void Knight Archery Store': 1.0,
    'Void Knight Magic Store': 1.0,
    'Warrior Guild Armoury': 1.2,
    'Warrior Guild Food Shop': 1.2,
    'Warrior Guild Potion Shop': 1.2,
    'Wayne\'s Chains! - Chainmail specialist.': 1.0,
    'Weapons galore': 1.1,
    'West Ardougne General Store': 1.2,
    'White Knight Armoury': 1.0,
    'William\'s Wilderness Cape Shop.': 1.0,
    'Wine Shop.': 1.0,
    'Yarnio\'s Baked Goods': 1.0,
    'Yarsul\'s Prodigious Pickaxes': 1.0,
    'Ye olde Tea Shoppe.': 1.0,
    'Zaff\'s Superior Staffs!': 1.0,
    'Zeke\'s Superior Scimitars.': 1.0,
    'Zenesha\'s Plate Mail Body Shop.': 1.0,
    '~ Uglug\'s stuffsies ~': 1.0,
};